# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d37a6709d29466016cab5380350bab4cd8724348675f92abaa27ce2cd1f01c8adf3b81701912b0b46561127044a7f386c9d68d3e0d008166c152f0be478759

test:
  secret_key_base: a835ef6f61d7ec6e5f6e86508fc527c03435793767f3def3b81ba1537cd1f5ef33365be6b434713f7a4ee3c79800e0e4aa5eee02bd37f8a05dc7819184903ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
